### ISSUE TITLE
No possible to rerun a verification after step check

### ISSUE THREAD

**Issue by schtrym** [kullervo16/checklist#1]
Once we check a step in a checklist, we must do some verification. 

If a verification is failed and we communicate that to the app, it is not possible to rerun this verification

![screenshot](https://cloud.githubusercontent.com/assets/3494830/16150955/9795128c-349a-11e6-87fe-062b51017c60.png)

**Comment by kullervo16** [comment]
Support for the re-execution was already there, but not for re-verification... The state CHECK_FAILED was considered an end-state..

Solution will be to provide a button when in state CHECK_FAILED to allow re-validation
