### ISSUE TITLE
Add a flag to mark a checklist template as "SubCheckList only"

### ISSUE THREAD

**Issue by schtrym** [kullervo16/checklist#11]
Some checklist template should only be used as **subchecklist**.

In the template of such a subchecklist, we should give meta data to flag this checklist as **subChecklistOnly**

With this flag, a template should not be usable from scratch.. but only usable from another *mother* checklist.

In the template and checklist screen, we could also add a filter to hide (default) such *subchecklist only" templates

**Comment by kullervo16** [comment]
I will make add a marker and place them at the bottom... since we have the upload/download options that are important to be used as examples/update the templates, I think hiding them may be confusing.. we'll see in practice.
