### ISSUE TITLE
Focus on edit field in Add Tag window

### ISSUE THREAD

**Issue by adconet** [kullervo16/checklist#114]
When adding a tag you get a window with 1 edit field to define the tag. It would be nice if this field has the focus so you can immediately start typing. Now you have to select the edit field first.

**Comment by kullervo16** [comment]
The field has the autofocus property, which works in my version of chrome... I do see that it doesn't work on firefox however... will try to set the focus another way that works in both...

**Comment by kullervo16** [comment]
ok, this seams to be hard... no mather how I tell firefox to focus on the element, just won't do it... can you tell me whether it is indeed firefox you're using (otherwise which browser/os)...

**Comment by adconet** [comment]
I was using an older version of Chrome (1 year old). Tested it now in an upgraded version and it works.
