### ISSUE TITLE
New step in standard deployment cheklists

### ISSUE THREAD

**Issue by zip4ever** [kullervo16/checklist#13]
Currently we are surprised by a chat that our deployment is done. 

It would be a good thing if the first step of the checlist is: "Contact the requestor that the deployment will be started".

This way we can better prepare and follow up ...

**Comment by kullervo16** [comment]
This is a comment on the content of the checklist you are using, not on the tool... since the development team has no idea what  your content is, we cannot help you :smiling_imp:
