### ISSUE TITLE
Error raised when using more than one / in the checklist id

### ISSUE THREAD

**Issue by schtrym** [kullervo16/checklist#14]
The checklist app do not work if we set a template id with more than one `/`

ex : `/vas/governance/development/architectureCheck`

It is also impossible to delete a checklist template with a name like that..

Possible Quick fix : do not allow template name with more than one `/ `

**Comment by kullervo16** [comment]
allowing multiple / in the path screws up the URL structure that was defined during the REST cleanup, so indeed a large impact...

not being able to delete them only applies to checklists created with versions prior to 0.8. You can delete/move them manually on the file store and then restart the repo.

Fix will be to refuse values with more than 1 / in the name client side..
