### ISSUE TITLE
Subchecklist is not green after completion

### ISSUE THREAD

**Issue by schtrym** [kullervo16/checklist#19]
I've completed a subchecklist but it does not appears as green in the parent checklist :

![issue 19](https://cloud.githubusercontent.com/assets/3494830/16801977/2f9fd32e-48fe-11e6-8642-a251882e9fff.png)

Here is the bundle with the used template

[project.zip](https://github.com/kullervo16/checklist/files/361368/project.zip)

**Comment by kullervo16** [comment]
Reason found : when the last entry of a subchecklist is a question, the completeness check for the parent was not executed.
