### ISSUE TITLE
Tags should not be case sensitive

### ISSUE THREAD

**Issue by kernixski** [kullervo16/checklist#27]
We can create tags with uppercase and lowercase.  Then we can create ACC, Acc and acc tags.  It allows "duplicate" tags.

The application should avoid this.  If a ACC tag already exists then the acc and Acc tags should not be created.  The application should instead use the ACC tag.

**Comment by kullervo16** [comment]
When adding a tag, we compare with the already existing ones.. if there is a case insensitive match, we use that one.. This fixes the Acc/ACC/acc part... 

For even a better match between acc/accept/acceptation, see #26 (in following release)
