### ISSUE TITLE
Sub checklists should be hidden in the checklist overview

### ISSUE THREAD

**Issue by kernixski** [kullervo16/checklist#47]

**Comment by kullervo16** [comment]
You can do the same filtering like in the templates...

**Comment by kernixski** [comment]
I prefer to send a smaller json body the the client.  I already implemented it locally this morning.  I will push it this evening on a branch.

**Comment by kernixski** [comment]
Push done in issues/47 branch

**Comment by kernixski** [comment]
No sub checklist is listed anymore, the tags from sub checklists are no more added in the tag cloud.  People are often looking for a checklist, not for a sub checklist.  People reach the sub checklist from the parent checklist.
