### ISSUE TITLE
No way to filter checklists with more than one tag

### ISSUE THREAD

**Issue by kernixski** [kullervo16/checklist#6]
It should be great to filter checklists with more than one tag.

Neither checklist/rest/checklist/list?tag=tag1&tag=tag2 nor checklist/rest/checklist/list?tag=tag1,ag2 seems to work.

checklist/rest/checklist/list?tag=tag1&tag=tag2  should work.

Or even better: checklist/rest/checklist/list;tag=tag1,tag2  ;o)

**Comment by zip4ever** [comment]
Indeed ... an easy filter system on checklists is also the thing that I am missing most in this application...

**Comment by kullervo16** [comment]
we now support 
* checklist/rest/milestones (all) and checklist/rest/milestones?filter=<comma separated list>
* checklist/rest/tags (all) and checklist/rest/tags?filter=<comma separated list>
* checklist/rest/checklists?tags=<comma separated list>&milestones=<comma separated list>

So you can list the tags/milestones in combination, and then use a combination of both tags and reached milestones to retrieve your checklist.

And to make sure you don't need to type that in your browser, the tagcloud now works as a query builder : when you select a tag, you will get a new tagcloud showing the other tags for only the checklists that have your initial tag... and you add each selected tag to a selection. Once your selection is complete, you go to the overview... And you can combine with milestones.
