### ISSUE TITLE
Bad resource name for checklist/get

### ISSUE THREAD

**Issue by kernixski** [kullervo16/checklist#8]
/checklist/rest/checklist/get?id=_checklist_id_ is not a good REST URI.  Should be /checklist/rest/checklists/_checklist_id_

GET /checklist/rest/checklists/_checklist_id_ should return the checklist.

**Comment by kullervo16** [comment]
clear... after your explication.

One of the reasons for passing the IDs as parameters was that this is more convenient for passing values with / in it... well, now modelled properly.

 I tried to clean up as much as possible, but feel free to review it and provide me some feedback to improve more.
