### ISSUE TITLE
What is the difference between an action with options and a question with options ?

### ISSUE THREAD

**Issue by kernixski** [kullervo16/checklist#80]
We should have only one way to ask question to the user.  The question seems to be the right way but, for now, the conditions expect selectedOption to be filled and this field is only filled with actions, not questions.

I prefer to use questions in my conditions.

What do you think about this ?

**Comment by kullervo16** [comment]
I admit the difference is subtle, but with an action with options you perform an action : by selecting the option you influence how the checklist is behaving (so you are making an action). The question construction is there to ask the user a question that s/he should reflect on, and we store the response for human interpretation... as you state, no influence (and not considered an action).

Another difference is that the questions support a wider range of answers (like free text), whereas for influencing the checklist, we only support the predefined choices, so if we would change it to questions, we need to restrict that as well..

So I do not see a large benefit of replacing this...

**Comment by kernixski** [comment]
In my point of view, a question is a question, no matter if the system or the users will use the answer. And an action is an action the user has to do. 

Steps should be able to depend on a question step (for single and multiple choices only, not for free text). 

The system should only check conditions with with values on questions, not on actions.

Actions can now be started to indicate to other users that the user is working on this action. But there is no reason to start questions. And because actions can be questions, I have to write additional code for actions that are questions. It should be simpler to have real actions that are actions only and questions which are the only way to specify questions in the system.

**Comment by kullervo16** [comment]
The start behavior indeed a new factor. Ok to go for questions, but indicate clearly (also in the validation messages) that you can only depend on questions with predefined answers.

**Comment by kernixski** [comment]
Ok :)
